baseURL = 'https://reyko.xyz/'
languageCode = 'fr-fr'
title = 'Blog de Reyko'
theme = 'hello-friend-ng'
defaultContentLanguage = "fr"

[params]
  subtitle = "Bienvenue sur mon blog"
  enableSharingButtons = true
  enableThemeToggle = true
  customCSS = ["css/custom.css"]

[taxonomies]
  category = "categories"

[permalinks]
  categories = "/writeups/categories/:slug"

[menu]
  [[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/writeups/"
    weight = 1

  [[menu.main]]
    identifier = "ctf"
    name = "CTF"
    url = "/ctf/"
    weight = 2

  [[menu.main]]
    identifier = "projets"
    name = "Projets"
    url = "/projets/"
    weight = 3

  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 4

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 5

